# Use postgres/example user/password credentials
version: "3.9"

services:
  postgres:
    image: postgres
    restart: always

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: jwt

    ports:
      - "5432:5432"
      